services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: journal_app
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'

  example-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://test:test@test-db:5432/journal_app
      JWT_SECRET: your-super-secret-jwt-key-at-least-32-characters-long-for-testing
      ALLOW_REGISTRATION: true
      PORT: 3001
      FRONTEND_URL: http://localhost:3001
    ports:
      - '3001:3001'
    depends_on:
      - test-db
# docker-compose -f docker-compose.test.yml up -d --remove-orphans
# docker-compose -f docker-compose.test.yml down
