services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: journal_app
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"

# docker-compose -f docker-compose.test.yml up -d
# docker-compose -f docker-compose.test.yml down
