<script lang="ts">
  import {
    Dumbbell,
    Brain,
    Heart,
    Zap,
    Target,
    BookOpen,
    Mountain,
    Utensils,
    Bed,
    User,
    Users,
    Briefcase,
    Home,
    Car,
    Palette,
    Music,
    Camera,
    Gamepad2,
    Coffee,
    Flower,
    Shield,
    Star,
    Award,
    TrendingUp,
    BarChart3,
    Activity,
    Apple,
    Baby,
    Battery,
    Bike,
    Bird,
    Book,
    BookMarked,
    Brush,
    Bug,
    Building,
    Bus,
    Calculator,
    Calendar,
    Cat,
    ChefHat,
    Clock,
    Cookie,
    Dog,
    DollarSign,
    File,
    FileText,
    Film,
    Fish,
    Folder,
    Gift,
    GraduationCap,
    Guitar,
    Hammer,
    Headphones,
    IceCream,
    Image,
    Keyboard,
    Key,
    Laptop,
    Leaf,
    Lightbulb,
    Lock,
    Mail,
    MapPin,
    MessageCircle,
    Mic,
    Microscope,
    Monitor,
    Mouse,
    PenTool,
    Phone,
    Pill,
    Pizza,
    Plane,
    Presentation,
    Rocket,
    Scissors,
    Ship,
    Smartphone,
    Snowflake,
    Soup,
    Sparkles,
    Sprout,
    Stethoscope,
    Sun,
    Tent,
    Timer,
    Train,
    TreePine,
    Trophy,
    Waves,
    Weight,
    Wifi,
    Wine,
    Wrench,
  } from 'lucide-svelte';

  let {
    icon,
    size = 20,
    class: className = '',
  }: {
    icon?: string | null;
    size?: number;
    class?: string;
  } = $props();

  const iconMap: Record<string, import('svelte').ComponentType> = {
    // Original icons
    dumbbell: Dumbbell,
    brain: Brain,
    heart: Heart,
    zap: Zap,
    target: Target,
    'book-open': BookOpen,
    mountain: Mountain,
    utensils: Utensils,
    bed: Bed,
    user: User,
    users: Users,
    briefcase: Briefcase,
    home: Home,
    car: Car,
    palette: Palette,
    music: Music,
    camera: Camera,
    'gamepad-2': Gamepad2,
    coffee: Coffee,
    flower: Flower,
    shield: Shield,
    star: Star,
    award: Award,
    'trending-up': TrendingUp,

    // New expanded icons
    activity: Activity,
    apple: Apple,
    baby: Baby,
    battery: Battery,
    bicycle: Bike,
    bike: Bike,
    bird: Bird,
    book: Book,
    'book-marked': BookMarked,
    brush: Brush,
    bug: Bug,
    building: Building,
    bus: Bus,
    calculator: Calculator,
    calendar: Calendar,
    cat: Cat,
    'chef-hat': ChefHat,
    clock: Clock,
    cookie: Cookie,
    dog: Dog,
    'dollar-sign': DollarSign,
    file: File,
    'file-text': FileText,
    film: Film,
    fish: Fish,
    folder: Folder,
    gift: Gift,
    'graduation-cap': GraduationCap,
    guitar: Guitar,
    hammer: Hammer,
    headphones: Headphones,
    'ice-cream': IceCream,
    image: Image,
    keyboard: Keyboard,
    key: Key,
    laptop: Laptop,
    leaf: Leaf,
    lightbulb: Lightbulb,
    lock: Lock,
    mail: Mail,
    'map-pin': MapPin,
    'message-circle': MessageCircle,
    mic: Mic,
    microscope: Microscope,
    monitor: Monitor,
    mouse: Mouse,
    'pen-tool': PenTool,
    phone: Phone,
    pill: Pill,
    pizza: Pizza,
    plane: Plane,
    'presentation-chart': Presentation,
    rocket: Rocket,
    scissors: Scissors,
    ship: Ship,
    smartphone: Smartphone,
    snowflake: Snowflake,
    soup: Soup,
    sparkles: Sparkles,
    sprout: Sprout,
    stethoscope: Stethoscope,
    sun: Sun,
    tent: Tent,
    timer: Timer,
    train: Train,
    'tree-pine': TreePine,
    trophy: Trophy,
    'user-heart': User,
    waves: Waves,
    weight: Weight,
    wifi: Wifi,
    wine: Wine,
    wrench: Wrench,
  };

  function getIconComponent(iconName: string | null | undefined) {
    if (!iconName) return BarChart3; // Default fallback icon
    return iconMap[iconName] || BarChart3;
  }

  // Create reactive component reference
  const IconComponent = $derived(getIconComponent(icon));
</script>

<IconComponent {size} class={className} />
