name: Dependabot Auto-Merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write
  checks: read
  statuses: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Wait for tests to succeed
        id: wait-for-tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Enable auto-merge for Dependabot PRs
        # Only auto-merge minor and patch updates, not major versions
        if: ${{ (steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch') && steps.wait-for-tests.outcome == 'success' }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
          echo "Auto-merge enabled for ${{ steps.metadata.outputs.update-type }} update after successful tests"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
