name: Tests

on:
  pull_request:
    branches: [main]
  # Allow this workflow to be called by other workflows
  workflow_call:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    # Add PostgreSQL service
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: example_app
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      # Test environment variables
      DATABASE_URL: postgres://test:test@localhost:5432/example_app
      JWT_SECRET: test-jwt-secret-at-least-32-characters-long-for-testing
      NODE_ENV: test
      PORT: 3000
      TZ: America/Los_Angeles
      ALLOW_REGISTRATION: true
      FRONTEND_URL: http://localhost:4173

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Cheap checks first
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run database migrations
        run: bun run db:migrate

      - name: Run type checking
        run: bun run check

      # Expensive checks
      - name: Run e2e tests
        run: bun run test:e2e
