name: Tests

on:
  pull_request:
    branches: [main]
  # Allow this workflow to be called by other workflows
  workflow_call:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    # Add PostgreSQL service
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: journal_app_hono_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      # Test environment variables
      DATABASE_URL: postgres://test:test@localhost:5432/journal_app_hono_test
      JWT_SECRET: test-jwt-secret-at-least-32-characters-long-for-testing
      NODE_ENV: test
      PORT: 3000
      TZ: America/Los_Angeles
      ALLOW_REGISTRATION: true
      FRONTEND_URL: http://localhost:4173

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Cheap checks first
      # Root dependencies (needed for workspace setup)
      - name: Install root dependencies
        working-directory: ./
        run: |
          # Use flexible install for Dependabot PRs, strict for others
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            bun install
          else
            bun install
          fi

      # Backend setup and tests
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          # Use flexible install for Dependabot PRs, strict for others
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            bun install
          else
            bun install
          fi

      - name: Run backend database migrations
        working-directory: ./
        run: bun run db:migrate

      - name: Run backend type checking
        working-directory: ./backend
        run: bun run check

      # Frontend setup and tests
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          # Use flexible install for Dependabot PRs, strict for others
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            bun install
          else
            bun install
          fi

      - name: Run frontend type checking
        working-directory: ./frontend
        run: bun run check

      - name: Run frontend linting
        working-directory: ./frontend
        run: bun run lint:eslint

      - name: Build frontend
        working-directory: ./frontend
        run: bun run build

      # Expensive checks
      - name: Run backend tests
        working-directory: ./backend
        run: bun test

        # TODO: Uncomment when frontend tests are ready
      # - name: Run frontend tests
      #   working-directory: ./frontend
      #   run: bun test
